name: 构建iOS越狱插件

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        
      - name: 设置构建环境
        run: |
          sudo apt-get update
          sudo apt-get install -y curl wget git make clang unzip bzip2 fakeroot dpkg dpkg-dev ldid
          
      - name: 设置Theos环境
        run: |
          # 创建Theos目录
          mkdir -p $GITHUB_WORKSPACE/theos
          # 克隆最新的Theos
          git clone --recursive https://github.com/theos/theos.git $GITHUB_WORKSPACE/theos
          # 安装SDKs
          mkdir -p $GITHUB_WORKSPACE/theos/sdks
          # 下载iPhoneOS SDK (16.2版本，可根据需要更改)
          wget https://github.com/xybp888/iOS-SDKs/archive/master.zip -O sdks.zip
          unzip sdks.zip
          cp -r iOS-SDKs-master/iPhoneOS16.2.sdk $GITHUB_WORKSPACE/theos/sdks/
          # 设置环境变量
          echo "THEOS=$GITHUB_WORKSPACE/theos" >> $GITHUB_ENV
          echo "PATH=$GITHUB_WORKSPACE/theos/bin:$PATH" >> $GITHUB_ENV
      
      - name: 构建项目
        run: |
          # 显示环境信息
          echo "当前目录: $(pwd)"
          ls -la
          
          # 确保Makefile包含rootless配置
          echo "验证Makefile中的rootless配置:"
          grep -E "THEOS_PACKAGE_SCHEME.*rootless" Makefile || echo "警告：Makefile中可能缺少rootless配置"
          
          # 构建项目 - 显式设置rootless方案
          make package THEOS=$GITHUB_WORKSPACE/theos THEOS_PACKAGE_DIR_NAME=build THEOS_PACKAGE_SCHEME=rootless
          
          # 显示生成的文件
          echo "构建输出:"
          ls -la build/
          
      - name: 上传构建结果
        uses: actions/upload-artifact@v3
        with:
          name: rootless-deb-package
          path: build/*.deb
          if-no-files-found: error 