name: build deb

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Check cache
        run: |
          echo upstream_heads=`git ls-remote https://github.com/roothide/theos | head -n 1 | cut -f 1`-`git ls-remote https://github.com/theos/sdks | head -n 1 | cut -f 1` >> $GITHUB_ENV

      - name: Use cache
        id: cache
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/theos
          key: ${{ runner.os }}-${{ env.upstream_heads }}

      - name: Prepare Theos
        uses: huami1314/theos-action@main

      - name: Setup GNU Make
        run: |
          echo "$(brew --prefix)/opt/make/libexec/gnubin" >> $GITHUB_PATH

      - name: Build package
        run: |
          # 确保packages目录存在
          mkdir -p packages
          # 修改Makefile中的输出路径
          sed -i '' 's/export THEOS_PACKAGE_DIR = $(CURDIR)/export THEOS_PACKAGE_DIR = $(CURDIR)\/packages/g' Makefile || true
          
          # 构建包
          make clean
          make package FINALPACKAGE=1 -j$(sysctl -n hw.ncpu)
          make package THEOS_PACKAGE_SCHEME=rootless FINALPACKAGE=1 -j$(sysctl -n hw.ncpu)
          make package THEOS_PACKAGE_SCHEME=roothide FINALPACKAGE=1 -j$(sysctl -n hw.ncpu)
          
          # 调试信息
          echo "构建完成，检查文件："
          find ${{ github.workspace }} -name "*.deb" -type f

      - name: Upload Deb packages
        uses: actions/upload-artifact@v4
        with:
          name: x
          path: ${{ github.workspace }}/packages/*.deb 
